apiVersion: v1
kind: Secret
metadata:
  name: ssl-certificate
type: kubernetes.io/tls
data:
data:
  tls.crt: |
    {{/* Dummy self‑signed certificate (base64 encoded) */}}
    {{- default "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCg==\n" .Values.tls.crt }}
  tls.key: |
    {{/* Dummy private key (base64 encoded) */}}
    {{- default "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQo=\n" .Values.tls.key }}
