apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
type: Opaque
data:
  YUBICO_SECRET_KEY: {{ .Values.yubico.secretKey.value | b64enc | quote }}
  DUO_SKEY: {{ .Values.duo.sKey.value | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.smtp.password.value | b64enc | quote }}
  SMTP_USERNAME: {{ .Values.smtp.username.value | b64enc | quote }}
  PUSH_INSTALLATION_ID: {{ .Values.pushNotifications.installationId.value | b64enc | quote }}
  PUSH_INSTALLATION_KEY: {{ .Values.pushNotifications.installationKey.value | b64enc | quote }}
  ADMIN_TOKEN: {{ .Values.adminToken.value | b64enc | quote }}