apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: "lscr.io/linuxserver/qbittorrent:latest"
          imagePullPolicy: Always
          env:
            - name: PUID
              value: {{ .Values.global.uid | quote }}
            - name: PGID
              value: {{ .Values.global.gid | quote }}
            - name: TZ
              value: {{ .Values.global.tz | quote }}
            - name: WEBUI_PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: p2p
              containerPort: 6881
              protocol: TCP
            - name: p2pudp
              containerPort: 6881
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          hostPath:
            path: {{ .Values.directories.config | quote }}
            type: Directory
        - name: data
          hostPath:
            path: {{ .Values.directories.media | quote }}
            type: Directory