apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-service
spec:
  selector:
    app: qbittorrent
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: p2p
      port: 6881
      targetPort: p2p
      protocol: TCP
    - name: p2pudp
      port: 6881
      targetPort: p2p
      protocol: UDP