apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      containers:
        - name: jellyseerr
          image: "ghcr.io/fallenbagel/jellyseerr:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5055
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: /app/config
              name: config
      volumes:
        - name: config
          hostPath:
            path: {{ .Values.directories.config | quote }}
            type: Directory