apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: "lscr.io/linuxserver/sonarr:latest"
          imagePullPolicy: Always
          env:
            - name: PUID
              value: {{ .Values.global.uid | quote }}
            - name: PGID
              value: {{ .Values.global.gid | quote }}
            - name: TZ
              value: {{ .Values.global.tz | quote }}
          ports:
            - name: http
              containerPort: 8989
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          hostPath:
            path: {{ .Values.directories.config | quote }}
            type: Directory
        - name: data
          hostPath:
            path: {{ .Values.directories.media | quote }}
            type: Directory