apiVersion: v2
name: hello-world
description: A web application to test a new cluster
sources:
  - https://github.com/nbaerts/local-cluster
maintainers:
  - name: nbaerts
type: application
version: 1.0.0
